/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_com_thecherno_decompressor_Decompressor
#define _Included_com_thecherno_decompressor_Decompressor
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jfloatArray JNICALL Java_com_thecherno_decompressor_Decompressor_RunDecompression(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif