/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_thecherno_decompressor_DisplayActivity_DisplayRenderer */

#ifndef _Included_com_thecherno_decompressor_DisplayActivity_DisplayRenderer
#define _Included_com_thecherno_decompressor_DisplayActivity_DisplayRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_thecherno_decompressor_DisplayActivity_DisplayRenderer
 * Method:    OnInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_thecherno_decompressor_DisplayActivity_00024DisplayRenderer_OnInit
  (JNIEnv *, jclass);

/*
 * Class:     com_thecherno_decompressor_DisplayActivity_DisplayRenderer
 * Method:    OnSurfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_thecherno_decompressor_DisplayActivity_00024DisplayRenderer_OnSurfaceChanged
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_thecherno_decompressor_DisplayActivity_DisplayRenderer
 * Method:    OnDraw
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_thecherno_decompressor_DisplayActivity_00024DisplayRenderer_OnDraw
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
